import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TicketCreate {
  @ApiProperty()
  ticketNumber: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  status: string;
}

export class Ticket {
  @ApiProperty()
  id: number;
  @ApiProperty()
  ticketNumber: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  status: string;
}
