import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TableAssignmentCreate {
  @ApiProperty()
  tableNumber: string;
  @ApiProperty()
  capacity: string;
  @ApiProperty()
  status: string;
}

export class TableAssignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  tableNumber: string;
  @ApiProperty()
  capacity: string;
  @ApiProperty()
  status: string;
}
