import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ResignationCreate {
  @ApiProperty()
  employeeName: string;
  @ApiProperty()
  resignationDate: string;
}

export class Resignation {
  @ApiProperty()
  id: number;
  @ApiProperty()
  employeeName: string;
  @ApiProperty()
  resignationDate: string;
}
