import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyVersionCreate {
  @ApiProperty()
  VersionNumber: number;
  @ApiProperty()
  ReleaseDate: string;
  @ApiProperty()
  PolicyID: number;
}

export class PolicyVersion {
  @ApiProperty()
  id: number;
  @ApiProperty()
  VersionNumber: number;
  @ApiProperty()
  ReleaseDate: string;
  @ApiProperty()
  PolicyID: number;
}
