/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyTag } from './PolicyTag.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyTagService } from './PolicyTag.service';
import { PolicyTagController } from './PolicyTag.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyTag])],
  providers: [PolicyTagService],
  exports: [PolicyTagService],
  controllers: [PolicyTagController],
})
export class PolicyTagModule {}
