/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { PolicyTag, PolicyTagCreate } from './dtos/PolicyTag.dto';
import { PolicyTagController } from './PolicyTag.controller';
import { PolicyTagService } from './PolicyTag.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyTagController', () => {
  let controller: PolicyTagController;
  let spyService: PolicyTagService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyTagService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyTagController],
      providers: [PolicyTagService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyTagController>(PolicyTagController);
    spyService = module.get<PolicyTagService>(PolicyTagService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyTagController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyTagController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyTag();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
