/**
 * This file generated by Apso.
 */
import { MenuModule } from './Menu/Menu.module';
import { TableAssignmentModule } from './TableAssignment/TableAssignment.module';
import { OrderModule } from './Order/Order.module';
import { PaymentModule } from './Payment/Payment.module';

export default [MenuModule, TableAssignmentModule, OrderModule, PaymentModule];
