/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  TableAssignment,
  TableAssignmentCreate,
} from './dtos/TableAssignment.dto';
import { TableAssignmentController } from './TableAssignment.controller';
import { TableAssignmentService } from './TableAssignment.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('TableAssignmentController', () => {
  let controller: TableAssignmentController;
  let spyService: TableAssignmentService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: TableAssignmentService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [TableAssignmentController],
      providers: [TableAssignmentService, ApiServiceProvider],
    }).compile();

    controller = module.get<TableAssignmentController>(
      TableAssignmentController,
    );
    spyService = module.get<TableAssignmentService>(TableAssignmentService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call TableAssignmentController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call TableAssignmentController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new TableAssignment();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
