/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  TableAssignment,
  TableAssignmentCreate,
} from './dtos/TableAssignment.dto';
import { TableAssignmentService } from './TableAssignment.service';

@Crud({
  model: {
    type: TableAssignment,
  },
  dto: {
    create: TableAssignmentCreate,
    update: TableAssignment,
    replace: TableAssignment,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('TableAssignments')
@ApiTags('TableAssignments')
export class TableAssignmentController implements CrudController<TableAssignment> {
  constructor(public service: TableAssignmentService) {}

  get base(): CrudController<TableAssignment> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple TableAssignments' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single TableAssignment' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single TableAssignment' })
  @ApiBody({
    type: TableAssignmentCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: TableAssignment,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleTableAssignments' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<TableAssignment>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single TableAssignment' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: TableAssignment,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single TableAssignment' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: TableAssignment,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single TableAssignment' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
