/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { TableAssignment } from './TableAssignment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TableAssignmentService } from './TableAssignment.service';
import { TableAssignmentController } from './TableAssignment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([TableAssignment])],
  providers: [TableAssignmentService],
  exports: [TableAssignmentService],
  controllers: [TableAssignmentController],
})
export class TableAssignmentModule {}
