import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class OrderCreate {
  @ApiProperty()
  orderId: string;
  @ApiProperty()
  menuItemId: string;
  @ApiProperty()
  quantity: string;
  @ApiProperty()
  orderStatus: string;
}

export class Order {
  @ApiProperty()
  id: number;
  @ApiProperty()
  orderId: string;
  @ApiProperty()
  menuItemId: string;
  @ApiProperty()
  quantity: string;
  @ApiProperty()
  orderStatus: string;
}
