/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  PolicyCategory,
  PolicyCategoryCreate,
} from './dtos/PolicyCategory.dto';
import { PolicyCategoryController } from './PolicyCategory.controller';
import { PolicyCategoryService } from './PolicyCategory.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyCategoryController', () => {
  let controller: PolicyCategoryController;
  let spyService: PolicyCategoryService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyCategoryService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyCategoryController],
      providers: [PolicyCategoryService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyCategoryController>(PolicyCategoryController);
    spyService = module.get<PolicyCategoryService>(PolicyCategoryService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyCategoryController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyCategoryController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyCategory();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
