/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyCategory } from './PolicyCategory.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyCategoryService } from './PolicyCategory.service';
import { PolicyCategoryController } from './PolicyCategory.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyCategory])],
  providers: [PolicyCategoryService],
  exports: [PolicyCategoryService],
  controllers: [PolicyCategoryController],
})
export class PolicyCategoryModule {}
