/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('session')
export class Session {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @IsOptional({ groups: [UPDATE] })
  @IsNotEmpty({ groups: [CREATE] })
  @Column({ type: 'varchar', length: 255, nullable: false })
  sessionName: string;

  @Column({ type: 'time' })
  startTime: string;

  @Column({ type: 'time' })
  endTime: string;

  @IsOptional({ groups: [UPDATE] })
  @Column({ type: 'text', nullable: true })
  description: string;

  // Associations
}
