/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Session } from './Session.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SessionService } from './Session.service';
import { SessionController } from './Session.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Session])],
  providers: [SessionService],
  exports: [SessionService],
  controllers: [SessionController],
})
export class SessionModule {}
