import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PaymentCreate {
  @ApiProperty()
  paymentId: string;
  @ApiProperty()
  orderId: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  paymentStatus: string;
}

export class Payment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  paymentId: string;
  @ApiProperty()
  orderId: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  paymentStatus: string;
}
