/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Attendance } from './Attendance.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AttendanceService } from './Attendance.service';
import { AttendanceController } from './Attendance.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Attendance])],
  providers: [AttendanceService],
  exports: [AttendanceService],
  controllers: [AttendanceController],
})
export class AttendanceModule {}
