/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Attendance, AttendanceCreate } from './dtos/Attendance.dto';
import { AttendanceController } from './Attendance.controller';
import { AttendanceService } from './Attendance.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('AttendanceController', () => {
  let controller: AttendanceController;
  let spyService: AttendanceService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: AttendanceService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AttendanceController],
      providers: [AttendanceService, ApiServiceProvider],
    }).compile();

    controller = module.get<AttendanceController>(AttendanceController);
    spyService = module.get<AttendanceService>(AttendanceService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call AttendanceController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call AttendanceController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Attendance();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
