import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AttendanceCreate {
  @ApiProperty()
  eventId: string;
  @ApiProperty()
  employeeId: string;
  @ApiProperty()
  attendanceStatus: string;
}

export class Attendance {
  @ApiProperty()
  id: number;
  @ApiProperty()
  eventId: string;
  @ApiProperty()
  employeeId: string;
  @ApiProperty()
  attendanceStatus: string;
}
