import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyCategoryCreate {
  @ApiProperty()
  CategoryName: string;
}

export class PolicyCategory {
  @ApiProperty()
  id: number;
  @ApiProperty()
  CategoryName: string;
}
