/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { PolicyVersion } from './PolicyVersion.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PolicyVersionService } from './PolicyVersion.service';
import { PolicyVersionController } from './PolicyVersion.controller';

@Module({
  imports: [TypeOrmModule.forFeature([PolicyVersion])],
  providers: [PolicyVersionService],
  exports: [PolicyVersionService],
  controllers: [PolicyVersionController],
})
export class PolicyVersionModule {}
