/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { PolicyVersion, PolicyVersionCreate } from './dtos/PolicyVersion.dto';
import { PolicyVersionService } from './PolicyVersion.service';

@Crud({
  model: {
    type: PolicyVersion,
  },
  dto: {
    create: PolicyVersionCreate,
    update: PolicyVersion,
    replace: PolicyVersion,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('PolicyVersions')
@ApiTags('PolicyVersions')
export class PolicyVersionController implements CrudController<PolicyVersion> {
  constructor(public service: PolicyVersionService) {}

  get base(): CrudController<PolicyVersion> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple PolicyVersions' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single PolicyVersion' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single PolicyVersion' })
  @ApiBody({
    type: PolicyVersionCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyVersion) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multiplePolicyVersions' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<PolicyVersion>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single PolicyVersion' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyVersion) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single PolicyVersion' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: PolicyVersion) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single PolicyVersion' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
