/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { PolicyVersion, PolicyVersionCreate } from './dtos/PolicyVersion.dto';
import { PolicyVersionController } from './PolicyVersion.controller';
import { PolicyVersionService } from './PolicyVersion.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PolicyVersionController', () => {
  let controller: PolicyVersionController;
  let spyService: PolicyVersionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PolicyVersionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PolicyVersionController],
      providers: [PolicyVersionService, ApiServiceProvider],
    }).compile();

    controller = module.get<PolicyVersionController>(PolicyVersionController);
    spyService = module.get<PolicyVersionService>(PolicyVersionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PolicyVersionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PolicyVersionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new PolicyVersion();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
