/**
 * This file generated by Apso.
 */ /* eslint @typescript-eslint/no-unused-vars: "off" */

import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
  Generated,
  JoinColumn,
  JoinTable,
  Index,
  Unique,
  PrimaryColumn,
} from 'typeorm';
import {
  IsOptional,
  IsString,
  MaxLength,
  IsNotEmpty,
  IsEmail,
  IsBoolean,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CrudValidationGroups } from '@nestjsx/crud';

const { CREATE, UPDATE } = CrudValidationGroups;

@Entity('policy_version')
export class PolicyVersion {
  // Fields
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ type: 'int' })
  VersionNumber: number;

  @Column({ type: 'date', nullable: false })
  ReleaseDate: string;

  @Column({ type: 'int' })
  PolicyID: number;

  // Associations
}
