import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SessionCreate {
  @ApiProperty()
  sessionName: string;
  @ApiProperty()
  startTime: string;
  @ApiProperty()
  endTime: string;
  @ApiProperty()
  description: string;
}

export class Session {
  @ApiProperty()
  id: number;
  @ApiProperty()
  sessionName: string;
  @ApiProperty()
  startTime: string;
  @ApiProperty()
  endTime: string;
  @ApiProperty()
  description: string;
}
