import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyAssignmentCreate {
  @ApiProperty()
  AssignedTo: string;
  @ApiProperty()
  AssignmentDate: string;
  @ApiProperty()
  PolicyID: number;
}

export class PolicyAssignment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  AssignedTo: string;
  @ApiProperty()
  AssignmentDate: string;
  @ApiProperty()
  PolicyID: number;
}
