/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Event } from './Event.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { EventService } from './Event.service';
import { EventController } from './Event.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Event])],
  providers: [EventService],
  exports: [EventService],
  controllers: [EventController],
})
export class EventModule {}
