import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyTagCreate {
  @ApiProperty()
  TagName: string;
}

export class PolicyTag {
  @ApiProperty()
  id: number;
  @ApiProperty()
  TagName: string;
}
