/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Menu } from './Menu.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { MenuService } from './Menu.service';
import { MenuController } from './Menu.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Menu])],
  providers: [MenuService],
  exports: [MenuService],
  controllers: [MenuController],
})
export class MenuModule {}
