import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class EventCreate {
  @ApiProperty()
  eventName: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  date: string;
  @ApiProperty()
  location: string;
  @ApiProperty()
  status: string;
}

export class Event {
  @ApiProperty()
  id: number;
  @ApiProperty()
  eventName: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  date: string;
  @ApiProperty()
  location: string;
  @ApiProperty()
  status: string;
}
