import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyDocumentCreate {
  @ApiProperty()
  Document: string;
  @ApiProperty()
  PolicyVersionID: number;
}

export class PolicyDocument {
  @ApiProperty()
  id: number;
  @ApiProperty()
  Document: string;
  @ApiProperty()
  PolicyVersionID: number;
}
