import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PolicyCreate {
  @ApiProperty()
  Title: string;
  @ApiProperty()
  Description: string;
  @ApiProperty()
  EffectiveDate: string;
  @ApiProperty()
  Status: string;
}

export class Policy {
  @ApiProperty()
  id: number;
  @ApiProperty()
  Title: string;
  @ApiProperty()
  Description: string;
  @ApiProperty()
  EffectiveDate: string;
  @ApiProperty()
  Status: string;
}
