/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Resignation, ResignationCreate } from './dtos/Resignation.dto';
import { ResignationController } from './Resignation.controller';
import { ResignationService } from './Resignation.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('ResignationController', () => {
  let controller: ResignationController;
  let spyService: ResignationService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: ResignationService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [ResignationController],
      providers: [ResignationService, ApiServiceProvider],
    }).compile();

    controller = module.get<ResignationController>(ResignationController);
    spyService = module.get<ResignationService>(ResignationService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call ResignationController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call ResignationController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Resignation();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
