/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Resignation } from './Resignation.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ResignationService } from './Resignation.service';
import { ResignationController } from './Resignation.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Resignation])],
  providers: [ResignationService],
  exports: [ResignationService],
  controllers: [ResignationController],
})
export class ResignationModule {}
